# Background
bg1 = pygame.image.load('images/bg/1.png').convert_alpha()
bg2 = pygame.image.load('images/bg/2.png').convert_alpha()
bg3 = pygame.image.load('images/bg/3.png').convert_alpha()
bg4 = pygame.image.load('images/bg/4.png').convert_alpha()
bg5 = pygame.image.load('images/bg/5.png').convert_alpha()
bg6 = pygame.image.load('images/bg/6.png').convert_alpha()
bg7 = pygame.image.load('images/bg/7.png').convert_alpha()
bg8 = pygame.image.load('images/bg/8.png').convert_alpha()
bg9 = pygame.image.load('images/bg/9.png').convert_alpha()
bg10 = pygame.image.load('images/bg/10.png').convert_alpha()
bg11 = pygame.image.load('images/bg/11.png').convert_alpha()
bg12 = pygame.image.load('images/bg/12.png').convert_alpha()
bg13 = pygame.image.load('images/bg/13.png').convert_alpha()
bg14 = pygame.image.load('images/bg/14.png').convert_alpha()
bg15 = pygame.image.load('images/bg/15.png').convert_alpha()
bg16 = pygame.image.load('images/bg/16.png').convert_alpha()
bg17 = pygame.image.load('images/bg/17.png').convert_alpha()
bg18 = pygame.image.load('images/bg/18.png').convert_alpha()
bg19 = pygame.image.load('images/bg/19.png').convert_alpha()
bg20 = pygame.image.load('images/bg/20.png').convert_alpha()
bg21 = pygame.image.load('images/bg/21.png').convert_alpha()
bg22 = pygame.image.load('images/bg/22.png').convert_alpha()
bg23 = pygame.image.load('images/bg/23.png').convert_alpha()
bg24 = pygame.image.load('images/bg/24.png').convert_alpha()
bg25 = pygame.image.load('images/bg/25.png').convert_alpha()

# Other
cursor_icon = pygame.image.load('images/cursor.png').convert_alpha()
jet_icon = pygame.image.load('images/jet.png').convert_alpha()
logo_icon = pygame.image.load('images/globe.png').convert_alpha()
